name: Issue Parser 🤓

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch the issue
        id: read-issue
        run:
          echo "body=$(gh issue view 19 --repo ${{ github.repo }} --json body --jq '.body')" >> $GITHUB_OUTPUT
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
        with:
          body: >
            ### Org name

            unified

            ### Handle

            unifiedjs

            ### Description

            content as structured data, powering @remarkjs, @rehypejs, @retextjs, and @redotjs, used to build things like @mdx-js, @prettier, @gatsbyjs, and so much more!

            ### Org category

            Web

            ### New category

            _No response_

            ### What makes this org awesome?

            Tons of useful repos, powers a lot of other orgs and projects, uses org discussions, good org readme, has a website, twitter, email, verified, and much more!

            ### Criteria

            - [X] I attest!

            ### Code of conduct

            - [X] I agree to follow `awesome-orgs`'s Code of Conduct
      - run: echo ${{ toJSON(steps.read-issue.outputs.body) }}
      - run: echo ${{ steps.read-issue.outputs.body }}
