name: Issue Parser 🤓

on:
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v2.0.0
      - run: echo ${{ toJSON(steps.parse.outputs.data) }}
      - run: echo ${{ steps.parse.outputs.data }}
